stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
