kind: Service
apiVersion: v1
metadata:
  name: node-helloserver-service
spec:
  selector:
    app: node-helloserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-helloserver
  labels:
    app: node-helloserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-helloserver
  template:
    metadata:
      labels:
        app: node-helloserver
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: node-helloserver
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
